const colors=['빨강','주황','노랑','초록','하늘색','파랑','보라','분홍','흰색'];
const shop=[['산호',50,'🪸'],['해초',50,'🌿'],['조개',50,'🐚'],['불가사리',70,'⭐'],['진주 조개',100,'🦪'],['조개 침대',100,'🛏️'],['해초 소파',120,'🛋️'],['산호 의자',120,'🪑'],['조개 테이블',100,'🪵'],['보물상자',150,'🎁'],['미니 등대',200,'🗼'],['기본 조명',50,'💡'],['블루 조명',100,'🔵'],['핑크 조명',100,'🩷'],['오로라 조명',250,'🌈'],['네온 조명',300,'💠'],['얕은 바다',100,'🌊'],['산호초',200,'🪸'],['심해',300,'🌌'],['야간 바다',300,'🌙'],['부산 광안리 테마',500,'🌉']];
const caps=[5,10,15,20,30];
let state=JSON.parse(localStorage.getItem('jellydex_state')||'null')||{coins:0,level:1,jellies:[],items:[]};
const save=()=>localStorage.setItem('jellydex_state',JSON.stringify(state));
const content=document.querySelector('#jellydexContent');
const jelly=(j)=>`<button class="pixel-jelly jelly-${j.colorIndex}" data-jelly="${j.id}"><span class="pixel-cap"></span><i></i><i></i><i></i><i></i></button><strong class="jelly-name">${j.name}</strong>`;
function render(tab='home'){
 document.querySelector('#coinCount').textContent=state.coins;
 if(tab==='home') content.innerHTML=`<section class="game-hero"><div><span class="pixel-kicker">DAILY DISCOVERY</span><h3>부산 바다에서<br><em>새 친구를 찾아요!</em></h3><p>해파리 사진을 인증하면 픽셀 해파리와 100코인을 받아요.</p><label class="scan-upload"><input id="jellyScan" type="file" accept="image/*"><span>📷 사진으로 해파리 인증</span></label><small id="scanStatus">AI 인증 대기 중 · 사진을 올려보세요</small></div><div class="game-orb">🪼<span>+100</span></div></section><section class="game-section"><div class="game-section-title"><h3>내 수조</h3><button data-tab="tank">모두 보기 →</button></div><div class="mini-tank">${state.jellies.slice(0,5).map(j=>`<div class="jelly-card">${jelly(j)}</div>`).join('')||'<p class="empty-state">첫 해파리를 인증해보세요!</p>'}</div></section>`;
 else if(tab==='tank') content.innerHTML=`<section class="game-section"><div class="game-section-title"><div><span class="pixel-kicker">AQUARIUM LV.${state.level}</span><h3>나의 수조 <small>${state.jellies.length}/${caps[state.level-1]}</small></h3></div><button class="upgrade-button" data-upgrade ${state.level===5?'disabled':''}>수조 업그레이드<br><b>🪙 300</b></button></div><div class="tank-scene">${state.jellies.map(j=>`<div class="tank-jelly" data-jelly="${j.id}">${jelly(j)}<span class="affection">♥ ${j.affection}</span></div>`).join('')||'<p class="empty-state">수조가 비어 있어요.</p>'}</div></section>`;
 else if(tab==='dex') content.innerHTML=`<section class="game-section"><div class="game-section-title"><div><span class="pixel-kicker">COLLECTION</span><h3>해파리 도감 <small>${state.jellies.length}마리</small></h3></div></div><div class="dex-grid">${state.jellies.map(j=>`<article class="dex-card">${jelly(j)}<small>${j.date} · ${j.color}</small><span>친밀도 ${j.affection} · ${j.stage}</span></article>`).join('')||'<p class="empty-state">인증한 해파리가 자동 등록됩니다.</p>'}</div></section>`;
 else if(tab==='shop') content.innerHTML=`<section class="game-section"><div class="game-section-title"><h3>수조 상점</h3></div><div class="shop-grid">${shop.map(x=>`<button class="shop-item" data-buy="${x[0]}" data-price="${x[1]}"><span>${x[2]}</span><b>${x[0]}</b><small>🪙 ${x[1]}</small></button>`).join('')}</div></section>`;
 else content.innerHTML=`<section class="profile-card"><div class="avatar">🧑‍🚀</div><span class="pixel-kicker">JELLY TRAINER</span><h3>바다 탐험가</h3><p>해파리 ${state.jellies.length}마리 · 수조 레벨 ${state.level}</p><div class="profile-stats"><span><b>${state.coins}</b>코인</span><span><b>${state.items.length}</b>장식</span></div></section>`;
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>render(b.dataset.tab));
 document.querySelector('#jellyScan')?.addEventListener('change',scan);
 document.querySelector('[data-upgrade]')?.addEventListener('click',()=>{if(state.level<5&&state.coins>=300){state.coins-=300;state.level++;save();render('tank')}else alert('수조 업그레이드에는 300코인이 필요해요.')});
 document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{let p=+b.dataset.price;if(state.coins<p)return alert('코인이 부족해요.');state.coins-=p;state.items.push(b.dataset.buy);save();render('shop')});
 document.querySelectorAll('[data-jelly]').forEach(b=>b.onclick=()=>{let j=state.jellies.find(x=>x.id===b.dataset.jelly);if(!j)return; j.affection=Math.min(100,j.affection+10);j.stage=j.affection>=70?'성체':j.affection>=35?'성장기':'아기';save();render('tank')});
}
function scan(e){let f=e.target.files[0];if(!f)return;document.querySelector('#scanStatus').textContent='AI가 사진 속 해파리를 분석하는 중…';setTimeout(()=>{if(state.jellies.length>=caps[state.level-1])return document.querySelector('#scanStatus').textContent='수조가 가득 찼어요. 먼저 업그레이드해 주세요.';let i=Math.floor(Math.random()*colors.length);state.jellies.push({id:Date.now().toString(),name:`Jelly ${state.jellies.length+1}`,color:colors[i],colorIndex:i,affection:10,stage:'아기',date:new Date().toLocaleDateString('ko-KR')});state.coins+=100;save();render();document.querySelector('#scanStatus').textContent='인증 성공! 해파리 획득 · +100코인';},900)}
document.querySelector('#jellydexLaunch').onclick=()=>{document.querySelector('#jellydexOverlay').classList.add('open');document.querySelector('#jellydexOverlay').setAttribute('aria-hidden','false');render()};
document.querySelector('#jellydexClose').onclick=()=>{document.querySelector('#jellydexOverlay').classList.remove('open');document.querySelector('#jellydexOverlay').setAttribute('aria-hidden','true')};
document.querySelectorAll('.jellydex-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.jellydex-tabs button').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.gameTab)});
